name: Test CI

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'dev', 'staging', 'main' ]

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Test on Push / Pull-Request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # setup node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ramyozi'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@ramyozi:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # run code formatter
      - name: Code Formatter
        run: yarn format

      # run lint test
      - name: Lint Test
        run: yarn lint

      # run unit test
      - name: Unit Test
        run: yarn test
